/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Contents: typeof import('./layouts/Contents.vue')['default']
    DesktopLayout: typeof import('./layouts/DesktopLayout.vue')['default']
    Treebar: typeof import('./layouts/Treebar.vue')['default']
  }
}
