/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./app/App.vue')['default']
    DesktopLayout: typeof import('./layouts/DesktopLayout.vue')['default']
    NxWelcome: typeof import('./app/NxWelcome.vue')['default']
  }
}
