/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./app/App.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    Contents: typeof import('./layouts/Contents.vue')['default']
    DesktopLayout: typeof import('./layouts/DesktopLayout.vue')['default']
    ExplorerBar: typeof import('./layouts/ExplorerBar.vue')['default']
    FileList: typeof import('./layouts/FileList.vue')['default']
    GridConfigDialog: typeof import('./layouts/dialogs/GridConfigDialog.vue')['default']
    Hover: typeof import('./components/Hover.vue')['default']
    PathTreeNode: typeof import('./components/PathTreeNode.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    ToggleSwitch: typeof import('./components/ToggleSwitch.vue')['default']
  }
}
