/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '[...mount]': typeof import('./../pages/sessions/[sessionId]/mount/[...mount].vue')['default']
    '[sessionId]': typeof import('./../pages/sessions/[sessionId]/index.vue')['default']
    App: typeof import('./../app/App.vue')['default']
    AppDialog: typeof import('./../app/AppDialog.vue')['default']
    Breadcrumb: typeof import('./../components/Breadcrumb.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Hover: typeof import('./../components/Hover.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Menu: typeof import('primevue/menu')['default']
    MenuDialog: typeof import('./../components/MenuDialog.vue')['default']
    Mount: typeof import('./../pages/sessions/[sessionId]/mount/index.vue')['default']
    MountFilterDialog: typeof import('./../dialogs/MountFilterDialog.vue')['default']
    MountGrid: typeof import('./../layouts/MountGrid.vue')['default']
    MountOrderDialog: typeof import('./../dialogs/MountOrderDialog.vue')['default']
    MountSortDialog: typeof import('./../dialogs/MountSortDialog.vue')['default']
    NewSessionDialog: typeof import('./../dialogs/NewSessionDialog.vue')['default']
    ObjectTree: typeof import('./../components/ObjectTree.vue')['default']
    OrderList: typeof import('primevue/orderlist')['default']
    Pages: typeof import('./../pages/index.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    PrimeIcon: typeof import('./../components/PrimeIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Sessions: typeof import('./../pages/sessions/index.vue')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    SplitContainer: typeof import('./../components/SplitContainer.vue')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
